Plutarch Numeric hierarchy
Plutonomicon/plutarch-plutus pull request #160
Opened 2022-01-21 06:56 UTC by sergesku

2022-01-21 09:47 UTC, L-as requested changes
In general looks good, very few missed hoists, etc., although I'm not really sure why you're removing the `Num` instances?

2022-01-21 09:47 UTC, L-as commented on Plutarch/Api/V1.hs
> -  deriving (PIntegral) via (PInteger)
?

2022-01-21 09:47 UTC, L-as commented on Plutarch/Builtin.hs
> +      toBool d = pfstBuiltin # (pasConstr # d) #== pconstant 1
Why?

2022-01-21 09:47 UTC, L-as commented on Plutarch/DataRepr.hs
> +    ind = pconstant $ natVal n
Why?

2022-01-21 09:47 UTC, L-as commented on Plutarch/Integer.hs
> -instance Num (Term s PInteger) where
Why remove this instance?

2022-01-21 09:47 UTC, L-as commented on Plutarch/Integer.hs
> +    ( plam $ \x i ->
do-syntax please

2022-01-21 09:47 UTC, L-as commented on Plutarch/Integer.hs
> +pexpBySquaring = pfix #$ plam f
This isn't hoisted.

2022-01-21 09:47 UTC, L-as commented on Plutarch/List.hs
> +     in go # xs # pzero
Why?

2022-01-21 09:47 UTC, L-as commented on Plutarch/Natural.hs
> +pnatFromIntUnsafe = pcon . PNatural
In general it should be `punsafe*`.

2022-01-21 09:47 UTC, L-as commented on Plutarch/Natural.hs
> +    phoistAcyclic
You can just use `pfromData` for integers here without all this complex logic. The argument passed to this function is `PAsData PNatural`, so we already know it's correct. No need to check anything.

2022-01-21 09:47 UTC, L-as commented on Plutarch/Natural.hs
> +  pdata x =
No need for the unnecessary lambda here either.

2022-01-21 10:52 UTC, sergesku commented
I`m not sure about `Num` and `PIntegral` instances.
I get the task from @kozross to replace `Num` and `Fractional` instances with the new `Numeric` hierarchy. 

And I must admit, using `pconstant` on numeric literals all the time is a pain.

2022-01-21 12:27 UTC, L-as commented
I think it's good to have the new classes, but I don't see why `Num` should be removed. It's quite convenient.

2022-01-21 12:57 UTC, sergesku commented
OK, I'll put them back

2022-01-28 14:03 UTC, L-as commented on Plutarch/Integer.hs
> +    ( plam $ \x i ->
We can't actually use do-syntax, because it breaks GHC 8.10.7...

2022-04-11 17:33 UTC, TotallyNotChase commented
I'm trying to get this ready for Plutarch 1.2, as part of `plutarch-extra`.

2022-04-25 17:40 UTC, L-as commented
@TotallyNotChase is this ready?

2022-04-26 06:17 UTC, TotallyNotChase commented
@L-as Not yet, I'm going to do some finishing touches post #435 and then we should get a review from Koz and fill in any missing pieces.

2025-08-12 22:56 UTC, closed without merging