Add PThese, PTheseData
Plutonomicon/plutarch-plutus pull request #355
Opened 2022-03-04 08:48 UTC by jhodgdev

This PR implements Plutarch analogues for [Data.These](https://hackage.haskell.org/package/these). Would it be possible to make `PTheseData` an instance of `PUnsafeLiftDecl`? I assume it would be, as `plutus-tx` appears to support `These`. I am unsure as to how to find the underlying PLC implementation.

2022-03-04 14:18 UTC, emiflake commented
> In Plutarch, we won't be going that route for value unions since it's rather inefficient.

I'm curious what's the approach that will be used instead? I know in the case of many Value functions the `These` can be eliminated with inline explicit branching, is this what you're envisioning?

2022-03-04 14:21 UTC, TotallyNotChase commented
AFAICT if `PValue`s (and `PMap`s) are required to be sorted at all times - there isn't a need for `These`.

2022-03-04 15:21 UTC, emiflake commented
But in the case of, say, `geq`, we would require traversing the full Value anyway, right? So in those cases the `These` overhead is a constant added cost, but not an algorithmic one.

2022-03-04 16:58 UTC, TotallyNotChase commented
Sorry, I'm not sure what you mean there. For `checkBinRel` in general, I also imagine iterating through both lists at the same time depending on the ordering of the keys would do:

```hs
checkBinRel :: Ord k => (Int -> Int -> Bool) -> [(k, Int)] -> [(k, Int)] -> Bool
checkBinRel f = inner
  where
    inner [] [] = True
    inner [] l = all (f 0 . snd ) l
    inner l [] = all (flip f 0 . snd) l
    inner a@((k1, v1):xs) b@((k2, v2):ys)
      | k1 < k2 = f v1 0 && inner xs b
      | k1 == k2 = f v1 v2 && inner xs ys
      | otherwise = f 0 v2 && inner a ys
```
I _imagine_ it'd have the same behavior assuming both the values/maps are sorted but I might be missing something here.

2022-03-08 08:12 UTC, t1lde commented on Plutarch/Api/V1/These.hs
> +  type PConstantRepr (PlutusThese.These a b) = [(Plutus.Data, Plutus.Data)]
If the intention is to match the Plutus These `ToData/FromData` repr,  you can derive via something like 
```haskell
deriving 
  via PConstantViaData (These a b) (PTheseData (PConstanted a) (PConstanted b))
  instance (...) => PConstant (These a b)
```

2022-03-08 08:17 UTC, t1lde commented
> I know in the case of many Value functions the `These` can be eliminated with inline explicit branching, is this what you're envisioning?

For Value utils I'd say eliminating the intermediate data would be right approach. & if necessary, retaining the scott-encoded `PThese` to return in some cases. `PThese` could be used at the haskell-level to have Value util implementations that look a little more like the plutus-tx ones.

2022-03-08 09:49 UTC, L-as requested changes
This could fit into `plutarch-extra`.

2022-03-08 09:50 UTC, L-as commented
Wait for that to be merged if you still want this. #351

2024-10-24 23:52 UTC, closed without merging