Add pshow instances
Plutonomicon/plutarch-plutus pull request #537
Opened 2022-08-10 21:41 UTC by tbidne

Added `PShow` instances to more types. The intention is to add these to `V2`, though most had to also be added to `V1` to prevent orphans.

Example output:
```haskell
-- without parens (pshow)
PTxOut [address = (PAddress [credential = (PPubKeyCredential [_0 = (PPubKeyHash 0x737472)]), stakingCredential = (PDNothing [])]), value = (PValue (PMap [])), datum = (POutputDatumHash [datumHash = (PDatumHash 0x68617368)]), referenceScript = (PDJust [_0 = (PScriptHash 0x7363726970742068617368)])]

-- with parens (pshow' True)
(PTxOut [address = (PAddress [credential = (PPubKeyCredential [_0 = (PPubKeyHash 0x737472)]), stakingCredential = (PDNothing [])]), value = (PValue (PMap [])), datum = (POutputDatumHash [datumHash = (PDatumHash 0x68617368)]), referenceScript = (PDJust [_0 = (PScriptHash 0x7363726970742068617368)])])
```

2022-08-11 02:11 UTC, SeungheonOh commented
This is great. Thank you

2022-08-11 14:04 UTC, L-as commented
This is nice, but optimally, we want to fix this in the general case. I.e., we want to derive it.

2022-08-11 14:04 UTC, L-as commented
@tbidne would you be willing to take a look at the generic stuff in `Plutarch.Show` and see if you can make it work for Data-encoded ADTs? #423

2022-08-15 12:38 UTC, L-as requested changes
Thanks! This is great.

2022-08-15 12:38 UTC, L-as commented on Plutarch/DataRepr/Internal.hs
> +        mconcat
Doesn't `<>` make a lot more sense here?

2022-08-15 12:38 UTC, L-as commented on Plutarch/DataRepr/Internal.hs
> +newtype PDataRecordShowHelper as s = PDataRecordShowHelper (Term s (PDataRecord as))
I'm honestly not a big fan of this helper datatype, there should be cleaner ways to do it, but it's not an issue honestly.
You don't have to change this.

2022-08-15 12:45 UTC, L-as commented
`./bin/format` BTW

2022-08-16 01:14 UTC, L-as commented
Huge thanks!

Wrt. PData and such, you can't derive PShow for PData. If you do, and you run pshow, it will just loop AFAICT, because it contains itself.

So I think that you should derive for POutputDatum, but put a manual instance on PData that says "<data>" or similar. Ideally, we'd have a proper PShow PData, but that can be done another day.

Thanks for this!

2022-08-16 17:10 UTC, L-as commented on Plutarch/DataRepr/Internal.hs
> +newtype PDataRecordShowHelper as s = PDataRecordShowHelper (Term s (PDataRecord as))
So normally, I'd do something with sop-core's SList/All to handle this. But it's not worth the effort IMO. It can't be made a lot cleaner.

2022-08-16 17:11 UTC, L-as commented on Plutarch/DataRepr/Internal.hs
> +newtype PDataRecordShowHelper as s = PDataRecordShowHelper (Term s (PDataRecord as))
E.g. [`cpara_SList`](https://hackage.haskell.org/package/generics-sop-0.5.1.2/docs/Generics-SOP.html#v:cpara_SList)

2022-08-16 17:12 UTC, L-as approved these changes
Beautiful!
Waiting for CI.

2022-08-16 17:16 UTC, merged