Utility functions for `PMaybe` and `PMaybeData`
Plutonomicon/plutarch-plutus pull request #561
Opened 2022-08-29 14:59 UTC by SeungheonOh

A one of new PRs that will be made for Liqwid-Plutarch-Extra upstreaming.

2022-08-31 17:01 UTC, L-as commented on plutarch-extra/Plutarch/Extra/Maybe.hs
> +{-# LANGUAGE PolyKinds #-}
? You can remove all three of these.

2022-08-31 17:02 UTC, L-as requested changes

2022-08-31 17:02 UTC, L-as commented on plutarch-extra/Plutarch/Extra/Maybe.hs
> +    forall (a :: S -> Type) (s :: S).
PType

2022-09-08 13:14 UTC, L-as commented
I can't merge this because the branch is out-of-date. I can't make it up-to-date because I can't modify the code in the branch.

2022-09-08 14:29 UTC, peter-mlabs commented
Updated the branch

2022-09-08 14:59 UTC, SeungheonOh commented
Thanks Peter, I'll do the same for `PMap` PR. For future PRs, do you want me to make branch on Plutonomicon repository? I doubt I have right permission for that.

2022-09-11 17:47 UTC, L-as requested changes

2022-09-11 17:47 UTC, L-as commented on plutarch-extra/Plutarch/Extra/Maybe.hs
> +pfromJust ::
All partial functions should have a `HasCallStack` constraint.

2022-09-11 17:47 UTC, L-as commented
Please do it in another PR.

2022-09-11 17:47 UTC, merged