Extra utilities for `PMap`
Plutonomicon/plutarch-plutus pull request #562
Opened 2022-08-29 15:17 UTC by SeungheonOh

Depending on #561

2022-08-31 17:04 UTC, L-as requested changes

2022-08-31 17:04 UTC, L-as commented on plutarch-extra/Plutarch/Extra/Map.hs
> + License: Apache 2.0
? I can't accept it with this in. The license must be MIT. In addition, we don't have any header like this anywhere, albeit I'd be OK with it being shortened to a 2 lines with just the original author and sponsor.

2022-08-31 17:04 UTC, L-as commented on plutarch-extra/Plutarch/Extra/Map.hs
> +    forall (k :: S -> Type) (v :: S -> Type) (s :: S).
PType

2022-09-22 19:07 UTC, L-as commented
I can't update this PR.

2022-09-22 19:17 UTC, SeungheonOh commented
I'll make a new PR from my fork. Liqwid-Labs fork seems to have problem with permission

2022-09-22 19:25 UTC, closed without merging