Add Intersection to Maps
Plutonomicon/plutarch-plutus pull request #604
Opened 2022-12-04 15:01 UTC by lemmon-714

I copied and renamed the union-function, except for the four marked spots. Manually tested only.

Refactoring is possible.

2022-12-05 09:33 UTC, lemmon-714 commented
My refactoring WIP is btw extracting the four marked spots into a config type; this would not only circumvent the copypasting but also allow adding more merge types; in particular 
- some kind of vector-arithmetic-like, which errors if there is any mismatch between keys;
- something to be used with PValue that drops a specified null (0 resp. the empty Map in that case), avoiding the need to pnormalize after each union. 

But that is postponed for premature optimisation reasons.

2022-12-21 13:22 UTC, L-as commented
Sorry for not getting back to this, I will take a look at this ASAP

2022-12-21 14:14 UTC, lemmon-714 commented
Lol no worries mate, I'm not in a rush. Thank you

2023-02-01 09:12 UTC, cjay requested changes
Looks good otherwise.

2023-02-01 09:12 UTC, cjay commented on Plutarch/Api/V1/AssocMap.hs
> +{- | Union two 'PMap's applying the given function to any two values that
Union doesn't seem to be a verb, so I'd word those as "build the union/intersection of".

2023-02-01 09:12 UTC, cjay commented on Plutarch/Api/V1/AssocMap.hs
> +{- | Union two 'PMap's applying the given function to any two data-encoded
Same here.

2023-02-01 09:12 UTC, cjay commented on Plutarch/Api/V1/AssocMap.hs
> +pinsecWith ::
`insec` is an unusual abbreviation, I'd just use `intersect`. Multiple places.

2023-02-01 09:12 UTC, cjay commented on Plutarch/Api/V1/AssocMap.hs
> +{- | Intersect two 'PMap's applying the given function to any two data-encoded
Instead of "applying", it could be more explicit: "merging values that share the same key, using the given function".

2023-02-07 11:31 UTC, cjay commented
Superseded by https://github.com/Plutonomicon/plutarch-plutus/pull/610.

2023-03-20 13:03 UTC, merged

2023-03-20 13:03 UTC, L-as commented
Thanks for the work! This has been merged now.