T4/clean up tests
Plutonomicon/plutarch-plutus pull request #731
Opened 2024-10-27 01:36 UTC by t4ccer

This unifies all three testsuites into one under `plutarch-testlib` and simplifies overall setup tremendously (removing roughly 1000 lines of support code). There's still a bit to do wrt moving stuff around but I've decided to stop here so goldens remain unchanged so it's somewhat manageable to review

2024-10-27 01:41 UTC, t4ccer commented on plutarch-testlib/goldens/extra.intervalutils.uplc.golden
> +                                                                                            (I 6)
That's correct, original tests had copy-paste error

2024-10-27 01:41 UTC, t4ccer commented on plutarch-testlib/goldens/extra.intervalutils.bench.golden
> -hull.6 not member of hull 3 5 {"exBudgetCPU":39309736,"exBudgetMemory":138428,"scriptSizeBytes":982}
As above

2024-10-27 19:55 UTC, kozross requested changes
The exposed identifiers in `plutarch-testlib` need `@since`s. Also, we need a changelog in `plutarch-testlib`.

2024-10-28 22:14 UTC, kozross approved these changes

2024-10-28 22:56 UTC, merged